name: ci-code-scan

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string
        description: "project working directory"

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
