name: ci-code-scan

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string
        description: "project working directory"
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: sonarcloud scan
        uses: SonarSource/sonarqube-scan-action@v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ inputs.workdir }}
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}

  semgrep-scan:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: run scan
        run: semgrep scan --config auto
