name: ci-docker-publish

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string
        description: "project working directory"

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6