name: ci-pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-js:
    uses: ./.github/workflows/ci-js.yaml@main
    with:
      workdir: ./api-js

  ci-code-scan:
    uses: ./.github/workflows/ci-code-scan.yaml@main
    needs: ci-js

  ci-docker:
    uses: ./.github/workflows/ci-docker-publish.yaml@main
    needs: ci-code-scan
