name: ci-pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-js:
    uses: ./.github/workflows/ci-js.yaml
    with:
      workdir: ./api-js

  ci-code-scan:
    uses: ./.github/workflows/ci-code-scan.yaml
    needs: ci-js
    with:
      workdir: ./api-js
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ci-docker:
    uses: ./.github/workflows/ci-docker-publish.yaml
    needs: ci-code-scan
    with:
      workdir: .
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  cd-render-stage:
    uses: ./.github/workflows/cd-render-stage.yaml
    needs: ci-docker
    with:
      service_url: "https://gh-actions-api-js.onrender.com"
    secrets:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

  cd-render-prd:
    uses: ./.github/workflows/cd-render-prd.yaml
    needs: cd-render-stage
    with:
      service_url: "https://gh-actions-api-js.onrender.com"
    secrets:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
